"""Constants for the Glosilo project."""

WORDFILE = "EO 15000 Tekstaro filtered with ESPDIC with English translation.txt"
WORDFILE_ADDITIONS = "additions.txt"
DIFFICULT_WORDLIST_FILE = "difficult.txt"
NAMELIST_FILE = "names.txt"

PUNCTUATION_REGEX = "([!?,.:;'“”—()" + '"' + "])"

# When you add a suffix here, you have to also find all words that end in that suffix
# but don't actually have that suffix (e.g. "fari" doesn't have the suffix "ar").
# See CORE_IMMUNE_WORDS below.
SUFFIXES: dict[str, str] = {
    "aĉ": "AWF",
    "ad": "CONT",
    "aĵ": "OBJ",
    "ar": "GRP",
    "ebl": "ABLE",
    "ec": "QUAL",
    "eg": "BIG",
    "ej": "PLC",
    "em": "TEND",
    "et": "DIM",
    "ig": "CAUS",
    "iĝ": "BECM",
    "il": "TOOL",
    "ind": "MRT",
    "ist": "IST",
    "uj": "BOX",
    "ul": "PERS",
    "it": "PST.PPRT",
    "int": "PST.APRT",
    "at": "PRS.PPRT",
    "ant": "PRS.APRT",
    "ot": "FUT.PPRT",
    "ont": "FUT.APRT",
}
# When you add a prefix here, you have to also find all words that start with that
# prefix but don't actually have that prefix (e.g. "disciplini" doesn't have the prefix
# "dis"). See CORE_IMMUNE_WORDS below.
PREFIXES: dict[str, str] = {
    "dis": "DIS",
    "ek": "EK",
    "mal": "OPP",
    "ne": "NOT",
}

# Suffixes which are normally applied to verbs.
VERB_SUFFIXES: set[str] = {
    "it",
    "int",
    "at",
    "ant",
    "ot",
    "ont",
    "il",
    "ig",
    "iĝ",
    "em",
    "ad",
    "ebl",
    "ind",
}

ENDING_ALTERNATIVES: dict[str, list[str]] = {
    "a": ["o", "e", "i"],
    "o": ["a", "e", "i"],
    "e": ["i", "o", "a"],
    "i": ["o", "a", "e"],
}


INTERJECTIONS: set[str] = {
    "aĉ",
    "adiaŭ",
    "ah",
    "aha",
    "aĥ",
    "aj",
    "amen",
    "ba",
    "be",
    "bis",
    "boj",
    "ĉaŭ",
    "fek",
    "fi",
    "fik",
    "fikfek",
    "ha",
    "halo",
    "haĉum",
    "haha",
    "he",
    "hej",
    "help",
    "hik",
    "hm",
    "ho",
    "ve",
    "hola",
    "hu",
    "hura",
    "ĥaĥa",
    "jen",
    "klik",
    "kvivit",
    "miaŭ",
    "mjaŭ",
    "muu",
    "nu",
    "oho",
    "oj",
    "okej",
    "pa",
    "paf",
    "pru",
    "sal",
    "ŝŝ",
    "ups",
    "ŭa",
    "ŭaŭ",
}

ARTICLES: set[str] = {"la"}

PREPOSITIONS: set[str] = {
    "al",
    "anstataŭ",
    "antaŭ",
    "apud",
    "ĉe",
    "ĉirkaŭ",
    "da",
    "de",
    "dum",
    "ekde",
    "ekster",
    "eksteren",
    "el",
    "en",
    "ĝis",
    "inter",
    "kontraŭ",
    "krom",
    "kun",
    "laŭ",
    "malgraŭ",
    "ol",
    "per",
    "plus",
    "po",
    "por",
    "post",
    "preter",
    "pri",
    "pro",
    "sen",
    "sub",
    "super",
    "sur",
    "tra",
    "trans",
}

NUMBERS: set[str] = {
    "nul",
    "unu",
    "du",
    "tri",
    "kvar",
    "kvin",
    "ses",
    "sep",
    "ok",
    "naŭ",
    "dek",
    "cent",
    "mil",
}

CONJUNCTIONS: set[str] = {
    "aŭ",
    "ĉar",
    "do",
    "kaj",
    "ke",
    "nek",
    "sed",
    "tamen",
}

AU_ADVERBS: set[str] = {
    "almenaŭ",
    "ambaŭ",
    "ankaŭ",
    "ankoraŭ",
    "apenaŭ",
    "baldaŭ",
    "ĉirkaŭ",
    "hieraŭ",
    "hodiaŭ",
    "kvazaŭ",
    "morgaŭ",
    "preskaŭ",
}

ADVERBS: set[str] = {
    "for",
    "jam",
    "ĵus",
    "mem",
    "nun",
    "nur",
    "plej",
    "pli",
    "plu",
    "tre",
    "tro",
    "tuj",
} | AU_ADVERBS

CORRELATIVE_PARTICLES: set[str] = {
    "ĉi",
    "ajn",
}

CORRELATIVES: set[str] = {
    "kiu",
    "tiu",
    "iu",
    "ĉiu",
    "neniu",
    "kio",
    "tio",
    "io",
    "ĉio",
    "nenio",
    "kiom",
    "tiom",
    "iom",
    "ĉiom",
    "neniom",
    "kiel",
    "tiel",
    "iel",
    "ĉiel",
    "neniel",
    "kiam",
    "tiam",
    "iam",
    "ĉiam",
    "neniam",
    "kie",
    "tie",
    "ie",
    "ĉie",
    "nenie",
    "kia",
    "tia",
    "ia",
    "ĉia",
    "nenia",
    "kial",
    "tial",
    "ial",
    "ĉial",
    "nenial",
    "kies",
    "ties",
    "ies",
    "ĉies",
    "nenies",
}

PRONOUNS: set[str] = {
    "mi",
    "vi",
    "li",
    "ŝi",
    "ĝi",
    "ni",
    "ili",
    "oni",
    "si",
    "ri",
}

# "Little words". These don't conform to the general orthography of Esperanto
# words. They are not verbs, nouns, adjectives, or adverbs formed from roots.
VORTETOJ: set[str] = (
    INTERJECTIONS
    | PREPOSITIONS
    | CONJUNCTIONS
    | NUMBERS
    | ADVERBS
    | CORRELATIVE_PARTICLES
    | CORRELATIVES
    | ARTICLES
    | PRONOUNS
)

# Words which look like they end in a plural or accusative ending, but don't.
STRIP_PLURAL_ACC_IMMUNE_WORDS: set[str] = {
    w for w in VORTETOJ if w.endswith(("n", "j"))
}

# Words which look like they end in a standard ending, but don't.
CORE_IMMUNE_WORDS: set[str] = {
    w for w in VORTETOJ if w.endswith(("a", "e", "i", "o", "u", "as", "is", "os", "us"))
}

# Any word which, when stripped of prefixes and suffixes, leave behind these cores,
# should be considered a core word and not stripped any further.
#
# Some of this was gleaned from reta-vortaro.de, and a lot from PIV.
# Some were from just running the glosser and finding incorrect glosses.
#
# I couldn't think of a reasonable algorithm that would detect these conditions.
#
# "faro" gets cored to "f+ar+o", which would be "a group of f's". But "faro" is
# actually a word, so why not far+o? I think an Esperantist would just say "aro de foj"
# rather than "faro".
#
# So we'd need access to a dictionary that only lists the core words, not all
# possible words. So a dictionary that lists "faranto" would fail to core this to
# "far+ant+o", because our algorithm would treat "faranto" as a core word. Even if we
# searched for words by getting rid of affixes one by one, we'd get to "faro" and then
# "fo" which we know to be incorrect.
#
# The ultimate problem is that we need a dictionary that shows the root of each word.
# So "faranto" and "faro" would have a root of "far". Wiktionary takes a stab at
# this: the definition for faranto contains the formula {{eo-form of|far|anto}},
# but the definition for faro contains no such formula. It does have something that
# could be useful in the etymology section:
# {{af|eo|fari|t1=to do|-o|pos2=nominal suffix}}
#
# In any case, we're stuck manually handling these situations.
ACX_ENDING_WORDS: set[str] = {
    "kaĉ",
    "klaĉ",
    "kraĉ",
    "laĉ",
    "maĉ",
    "plaĉ",
    "taĉ",
}
AD_ENDING_WORDS: set[str] = {
    "grad",
    "invad",
    "iomgrad",
    "kamarad",
    "kanad",
    "krad",
    "laŭgrad",
    "nead",
    "nomad",
    "parad",
    "persvad",
}
AJX_ENDING_WORDS: set[str] = {
    "laĵ",
}
AR_ENDING_WORDS: set[str] = {
    "akapar",
    "artefar",
    "avar",
    "bar",
    "bonfar",
    "ĉar",
    "ĉirkaubar",
    "deklar",
    "elfar",
    "elstar",
    "erar",
    "far",
    "februar",
    "flar",
    "har",
    "januar",
    "jar",
    "klar",
    "kompar",
    "kontraŭstar",
    "koŝmar",
    "knar",
    "kvar",
    "najbar",
    "ordinar",
    "par",
    "popular",
    "prepar",
    "refar",
    "registrar",
    "restar",
    "ripar",
    "star",
    "studjar",
    "ŝpar",
    "urbregistar",
    "var",
}
EBL_ENDING_WORDS: set[str] = {
    "febl",
}
EC_ENDING_WORDS: set[str] = {
    "dec",
    "spec",
}
EG_ENDING_WORDS: set[str] = {
    "fleg",
    "koleg",
    "laŭtleg",
    "leg",
    "neg",
    "preleg",
    "reg",
    "releg",
    "seg",
    "superreg",
    "teg",
    "voĉleg",
}
EJ_ENDING_WORDS: set[str] = {
    "bej",
    "gej",
    "plej",
}
EM_ENDING_WORDS: set[str] = {
    "alprem",
    "blasfem",
    "disprem",
    "ekstrem",
    "elprem",
    "ĝem",
    "kunprem",
    "piedprem",
    "prem",
    "problem",
    "rem",
    "sem",
    "sistem",
    "subprem",
    "tem",
    "trem",
}
ET_ENDING_WORDS: set[str] = {
    "aĉet",
    "almet",
    "almozpet",
    "deĵet",
    "dekret",
    "demet",
    "disĵet",
    "disket",
    "dismet",
    "elaĉet",
    "elĵet",
    "elmet",
    "enket",
    "enmet",
    "fet",
    "forĵet",
    "formet",
    "gazet",
    "impet",
    "intermet",
    "interpret",
    "ĵet",
    "komplet",
    "kontraŭmet",
    "kret",
    "kunmet",
    "kviet",
    "met",
    "obĵet",
    "pardonpet",
    "pet",
    "pret",
    "profet",
    "reĵet",
    "remet",
    "ret",
    "ripet",
    "sekret",
    "siluet",
    "stilet",
    "subaĉet",
    "submet",
    "surmet",
    "tret",
    "trumpet",
    "vet",
}
IG_ENDING_WORDS: set[str] = {
    "alig",
    "eksig",
    "goril",
    "instig",
    "korlig",
    "kunlig",
    "lig",
    "navig",
}
IGX_ENDING_WORDS: set[str] = set()
IL_ENDING_WORDS: set[str] = {
    "asimil",
    "babil",
    "bil",
    "bril",
    "ekzil",
    "facil",
    "ĝentil",
    "jubil",
    "kompil",
    "konsil",
    "mil",
    "mutil",
    "rebril",
    "senutil",
    "ŝil",
    "simil",
    "subtil",
    "trankvil",
    "trembril",
    "util",
}
IND_ENDING_WORDS: set[str] = {
    "blind",
}
IST_ENDING_WORDS: set[str] = {
    "asist",
    "eksist",
    "hist",
    "insist",
    "konsist",
    "kuneksist",
    "persist",
    "rezist",
}
UJ_ENDING_WORDS: set[str] = set()
UL_ENDING_WORDS: set[str] = {
    "akumul",
    "alkohol-brul",
    "angul",
    "bluokul",
    "brul",
    "bul",
    "bunsen-brul",
    "celtabul",
    "cirkul",
    "duoninsul",
    "ekbrul",
    "enkalkul",
    "forbrul",
    "formul",
    "friul",
    "gratul",
    "insul",
    "kalkul",
    "konsul",
    "kul",
    "kvarangul",
    "lul",
    "makul",
    "manipul",
    "memortabul",
    "molekul",
    "mul",
    "nebul",
    "okul",
    "postul",
    "regul",
    "rektangul",
    "respegul",
    "rul",
    "ŝaktabul",
    "sangomakul",
    "sanregul",
    "senmakul",
    "skrupul",
    "spegul",
    "stimul",
    "stratangul",
    "tabul",
    "triangul",
    "ulul",
}
AT_ENDING_WORDS: set[str] = {
    "abat",
    "adekvat",
    "advokat",
    "amrilat",
    "animstat",
    "aparat",
    "aristokrat",
    "aŭtomat",
    "aŭtoritat",
    "bat",
    "blat",
    "boat",
    "bofrat",
    "bonstat",
    "burokrat",
    "dat",
    "debat",
    "delikat",
    "demokrat",
    "dilat",
    "drat",
    "ekspluat",
    "fakultat",
    "flat",
    "frat",
    "gefrat",
    "glat",
    "granat",
    "grat",
    "gvat",
    "hepat",
    "iniciat",
    "interrilat",
    "kandidat",
    "karitat",
    "kat",
    "klimat",
    "komitat",
    "kompat",
    "konstat",
    "kravat",
    "kroat",
    "kvadrat",
    "labormerkat",
    "laŭreat",
    "limdat",
    "magnat",
    "majoritat",
    "mandat",
    "manplat",
    "mat",
    "mecenat",
    "membroŝtat",
    "mensostat",
    "merkat",
    "minoritat",
    "monat",
    "mortbat",
    "naskiĝdat",
    "neadekvat",
    "pactraktat",
    "palat",
    "piedbat",
    "pirat",
    "plenumkomitat",
    "prieksperimentat",
    "prioritat",
    "protektorat",
    "rat",
    "rebat",
    "rilat",
    "sabat",
    "sakstrat",
    "salat",
    "sanstat",
    "sat",
    "ŝat",
    "senat",
    "senŝpat",
    "sindikat",
    "soldat",
    "sortobat",
    "ŝpat",
    "stat",
    "ŝtat",
    "strat",
    "subŝtat",
    "tomat",
    "trabat",
    "traŭmat",
    "universitat",
}
IT_ENDING_WORDS: set[str] = {
    "apetit",
    "biskvit",
    "brit",
    "ĉefdelegit",
    "cirkvit",
    "civit",
    "deficit",
    "efrit",
    "ekscit",
    "elglit",
    "elit",
    "emerit",
    "enlit",
    "evit",
    "glit",
    "hezit",
    "hobit",
    "imit",
    "incit",
    "invit",
    "kapacit",
    "kompromit",
    "kreit",
    "krucmilit",
    "kvalit",
    "lit",
    "medit",
    "merit",
    "milit",
    "mit",
    "mondmilit",
    "orbit",
    "parazit",
    "profit",
    "rit",
    "satelit",
    "senhezit",
    "spirit",
    "spit",
    "split",
    "sprit",
    "subit",
    "ŝvit",
    "tradicio-lig",
    "vit",
    "vizit",
    "zenit",
}
OT_ENDING_WORDS: set[str] = {
    "anekdot",
    "bankrot",
    "balot",
    "bojkot",
    "bot",
    "dorlot",
    "dot",
    "florpot",
    "fot",
    "frot",
    "grot",
    "idiot",
    "komplot",
    "kot",
    "kvot",
    "lot",
    "mot",
    "not",
    "piednot",
    "pilot",
    "pot",
    "sabot",
}
ANT_ENDING_WORDS: set[str] = {
    "adjutant",
    "adoleskant",
    "ĉefleŭtenant",
    "diamant",
    "eksprezidant",
    "eldonkvant",
    "elefant",
    "gant",
    "gigant",
    "grimpoplant",
    "hant",
    "kant",
    "konsonant",
    "konstant",
    "kunkant",
    "kvant",
    "lant",
    "leŭtenant",
    "luigant",
    "plant",
    "popolkant",
    "transplant",
    "vant",
    "vicprezidant",
}
INT_ENDING_WORDS: set[str] = {
    "labirint",
    "montopint",
    "piedpint",
    "pint",
    "tint",
}
ONT_ENDING_WORDS: set[str] = {
    "alfront",
    "bankkont",
    "energifont",
    "font",
    "front",
    "glacimont",
    "hont",
    "horizont",
    "intermont",
    "konfront",
    "kont",
    "mont",
    "pont",
    "rakont",
    "renkont",
    "tont",
    "volont",
}
DIS_STARTING_WORDS: set[str] = {
    "disĉipl",
    "disciplin",
    "disdegn",
    "disec",
    "disert",
    "disertaci",
    "diserv",
    "disfori",
    "disident",
    "disip",
    "disk",
    "disking",
    "diskodorm",
    "diskotek",
    "diskret",
    "diskriminaci",
    "diskturn",
    "diskurs",
    "diskut",
    "diskutrond",
    "disleksi",
    "disoci",
    "disonanc",
    "dispel",
    "dispepsi",
    "dispne",
    "dispon",
    "disprozi",
    "disput",
    "dist",
    "distanc",
    "distiĥ",
    "distik",
    "distil",
    "disting",
    "distr",
    "distribu",
    "distrikt",
    "distrofi",
    "disturb",
}
EK_STARTING_WORDS: set[str] = {
    "ekart",
    "ekidn",
    "ekimoz",
    "ekin",
    "ekip",
    "eklez",
    "eklips",
    "ekolog",
    "ekonom",
    "ekonomik",
    "ekosistem",
    "ekran",
    "eksces",
    "ekscit",
    "eksklud",
    "eksklusiv",
    "ekskurs",
    "eksmod",
    "ekspanc",
    "ekspedic",
    "eksperiment",
    "ekspertiz",
    "eksplicit",
    "eksplik",
    "eksplod",
    "ekspluat",
    "ekspon",
    "eksport",
    "ekspozic",
    "ekspres",
    "eksprezident",
    "ekstaz",
    "ekster",
    "eksterland",
    "eksterm",
    "eksternorm",
    "eksterordinar",
    "eksterter",
    "ekstradic",
    "ekstravaganc",
    "ekstrem",
    "ekstremdekstr",
    "ekvador",
    "ekvivalent",
    "ekzakt",
    "ekzamen",
    "ekzekut",
    "ekzempl",
    "ekzerc",
    "ekzil",
    "ekzist",
    "ekzot",
    "ekzotik",
}
MAL_STARTING_WORDS: set[str] = {
    "malakit",
    "maleol",
    "malgraŭ",
    "malic",
}
NE_STARTING_WORDS: set[str] = {
    "nebul",
    "neces",
    "nederland",
    "negativ",
    "neglekt",
    "negoc",
    "negr",
    "neĝ",
    "nek",
    "nekrolog",
    "neni",
    "neniam",
    "neniom",
    "neniu",
    "neniel",
    "nenies",
    "nenio",
    "neologism",
    "nepr",
    "nerv",
    "nervoz",
    "nest",
    "neŭtral",
}
FAKEOUT_WORDS : set[str] = {
    "ĉiela",  # Looks like adjective form of ĉiel.
    "ĉielo",  # Looks like noun form of ĉiel.
}

CORE_IMMUNE_CORES: set[str] = (
     ACX_ENDING_WORDS
    | AD_ENDING_WORDS
    | AJX_ENDING_WORDS
    | AR_ENDING_WORDS
    | EBL_ENDING_WORDS
    | EC_ENDING_WORDS
    | EG_ENDING_WORDS
    | EJ_ENDING_WORDS
    | EM_ENDING_WORDS
    | ET_ENDING_WORDS
    | IG_ENDING_WORDS
    | IGX_ENDING_WORDS
    | IL_ENDING_WORDS
    | IND_ENDING_WORDS
    | IST_ENDING_WORDS
    | UJ_ENDING_WORDS
    | UL_ENDING_WORDS
    | AT_ENDING_WORDS
    | IT_ENDING_WORDS
    | OT_ENDING_WORDS
    | ANT_ENDING_WORDS
    | INT_ENDING_WORDS
    | ONT_ENDING_WORDS
    | DIS_STARTING_WORDS
    | EK_STARTING_WORDS
    | NE_STARTING_WORDS
    | MAL_STARTING_WORDS
    | FAKEOUT_WORDS
)

# Words which should not be glossed. Generally in the top 100 most common words in
# Esperanto.
COMMON_WORDS: set[str] = {
    # Articles, conjunctions, subphrase introducers, adverbs
    "la",
    "kaj",
    "ne",
    "ke",
    "por",
    "sed",
    "kun",
    "pli",
    "plej",
    "aŭ",
    "nur",
    "ankaŭ",
    "ĉu",
    "se",
    "ĉar",
    "dum",
    "eĉ",
    "jam",
    "nun",
    "tre",
    "tamen",
    "ja",
    "do",
    "ĝis",
    "mem",
    "ankoraŭ",
    "ajn",
    # Prepositions
    "de",
    "en",
    "al",
    "pri",
    "el",
    "sur",
    "per",
    "da",
    "pro",
    "post",
    "ol",
    "ĉe",
    "inter",
    "laŭ",
    "antaŭ",
    "kontraŭ",
    "je",
    # Derivations from prepositions
    #"posta",
    #"poste",
    #"antaŭa",
    #"antaŭe",
    #"kontraŭa",
    #"kontraŭe",
    # Pronouns
    "mi",
    "mia",
    "li",
    "lia",
    "ili",
    "ilia",
    "vi",
    "via",
    "ĝi",
    "ĝia",
    "si",
    "sia",
    "ŝi",
    "oni",
    "ni",
    "nia",
    # Table words
    "kiu",
    "tiu",
    "iu",
    "ĉiu",
    "neniu",
    "kio",
    "tio",
    "io",
    "ĉio",
    "nenio",
    "kiom",
    "tiom",
    "iom",
    "ĉiom",
    "neniom",
    "kiel",
    "tiel",
    "iel",
    "ĉiel",
    "neniel",
    "kiam",
    "tiam",
    "iam",
    "ĉiam",
    "neniam",
    "kie",
    "tie",
    "ie",
    "ĉie",
    "nenie",
    "kia",
    "tia",
    "ia",
    "ĉia",
    "nenia",
    "kial",
    "tial",
    "ial",
    "ĉial",
    "nenial",
    "kies",
    "ties",
    "ies",
    "ĉies",
    "nenies",
    # Other (literally)
    "alio",
    "alia",
    # This
    "ĉi",
    # Nouns and adjectives
    "jaro",
    "granda",
    "homo",
    "lingvo",
    "lando",
    "esperanto",
    "nova",
    "multa",
    "tute",
    "kelka",
    "tuta",
    "internacia",
    # Verbs
    "esti",
    "veni",
    "okazi",
    "scii",
    "vidi",
    "voli",
    "devi",
    "havi",
    "povi",
    "diri",
    "fari",
    # Cardinals
    "unu",
    "du",
    "tri",
    "kvar",
    "kvin",
    "ses",
    "sep",
    "ok",
    "naŭ",
    "dek",
    "cent",
    "mil",
    # Ordinals
    "unua",
    "dua",
    "tria",
    "kvara",
    "kvina",
    "sesa",
    "sepa",
    "oka",
    "naŭa",
    "deka",
    "centa",
    "mila",
    # Named numbers
    "unuo",
    "duo",
    "trio",
    "kvaro",
    "kvino",
    "seso",
    "sepo",
    "oko",
    "naŭo",
    "deko",
    "cento",
    "milo",
}
